/**
 * Automated test suite for AreWee-Optimizer v2.4.30
 * Tests:
 * 1. Cockpit tools (8 items) and functions (5 items) generated by analyzeSystem
 * 2. Per-tool ON/OFF states in cockpitFunctions (Lazyload, JS-optimering, CSS-generering, Google Fonts, Brandvägg)
 * 3. Absence of "nativ" in states
 * 4. Section headers in index.html (Verktyg, Funktioner, Identifierade risker)
 * 5. Sync plugin PHP version and security
 * 6. Version consistency across all modules (v2.4.30)
 * 7. Exporter Second Opinion report generation
 * 8. app.js and rules.js syntax validation
 */

const fs = require('fs');
const vm = require('vm');
const assert = require('assert');

console.log("=========================================");
console.log(" Running AreWee-Optimizer v2.4.30 Tests  ");
console.log("=========================================");

// Setup mock browser environment
const context = {
  console: console,
  TextEncoder: TextEncoder,
  TextDecoder: TextDecoder,
  window: {},
  document: {
    getElementById: () => null,
    querySelectorAll: () => [],
    createElement: () => ({ appendChild: () => {}, setAttribute: () => {}, style: {}, classList: { add: () => {}, remove: () => {} } })
  },
  navigator: { clipboard: { writeText: async () => {} } },
  localStorage: { getItem: () => null, setItem: () => {}, removeItem: () => {} },
  state: {
    rawInputs: {},
    parsedData: {},
    activeSite: "default",
    uploadMetadata: {},
    analysisResults: null,
    activeTab: "overview",
    activeRiskFilter: "all"
  }
};
vm.createContext(context);

// Load rules.js and exporter.js into context
const rulesCode = fs.readFileSync(__dirname + '/../js/rules.js', 'utf8');
const exporterCode = fs.readFileSync(__dirname + '/../js/exporter.js', 'utf8');

vm.runInContext(rulesCode, context);
vm.runInContext(exporterCode, context);

let passedTests = 0;

function runTest(name, fn) {
  try {
    fn();
    console.log(`✅ PASS: ${name}`);
    passedTests++;
  } catch (err) {
    console.error(`❌ FAIL: ${name}`);
    console.error(err);
    process.exit(1);
  }
}

// Test 1: Cockpit Tools and Functions structure
runTest("Cockpit Tools & Functions data structure and states", () => {
  const mockSys = {
    server: { type: "LiteSpeed", php_version: "8.2.1", memory_limit: "512M" },
    active_plugins: [
      { name: "LiteSpeed Cache", version: "7.1.1", slug: "litespeed-cache" },
      { name: "WooCommerce", version: "9.8.0", slug: "woocommerce" },
      { name: "Wordfence Security", version: "8.0.4", slug: "wordfence" },
      { name: "Elementor", version: "3.28.3", slug: "elementor" }
    ],
    theme: { name: "Astra", version: "4.8.0" }
  };
  const mockWoo = {
    cart_page_id: 10,
    checkout_page_id: 11,
    active_gateways: [{ id: "kco", title: "Klarna Checkout" }]
  };
  const mockElem = {
    version: "3.28.3",
    css_print_method: "external",
    google_fonts: true,
    e_lazy_load_images: "inactive"
  };
  const mockWf = {
    firewall_mode: "enabled",
    ip_header: "REMOTE_ADDR"
  };
  const mockTheme = { name: "Astra", version: "4.8.0" };
  const mockSettings = {
    media_lazy: "1",
    optm_js_defer: "2",
    optm_css_async: "1",
    optm_ggfonts_rm: "0",
    "cache-exc": "checkout\nkassa\nvarukorg\ncart"
  };

  const results = context.analyzeSystem(mockSys, mockWoo, mockWf, mockElem, mockSettings, "", "", mockTheme, null);

  assert(results, "Results must exist");
  assert(Array.isArray(results.cockpitTools), "cockpitTools must be an array");
  assert.strictEqual(results.cockpitTools.length, 8, "Must have exactly 8 cockpit tools");

  assert(Array.isArray(results.cockpitFunctions), "cockpitFunctions must be an array");
  assert.strictEqual(results.cockpitFunctions.length, 5, "Must have exactly 5 cockpit functions");

  const fnIds = results.cockpitFunctions.map(f => f.id);
  assert(fnIds.includes("lazyload"), "Must include lazyload");
  assert(fnIds.includes("js_opt"), "Must include js_opt");
  assert(fnIds.includes("css_gen"), "Must include css_gen");
  assert(fnIds.includes("google_fonts"), "Must include google_fonts");
  assert(fnIds.includes("firewall"), "Must include firewall");

  results.cockpitFunctions.forEach(fn => {
    assert(fn.name, `Function ${fn.id} must have a name`);
    assert(fn.status, `Function ${fn.id} must have a status`);
    assert(Array.isArray(fn.tools), `Function ${fn.id} must have tools array`);
    assert(fn.tools.length >= 2, `Function ${fn.id} must have at least 2 tools`);
    fn.tools.forEach(t => {
      assert(t.name, "Tool must have name");
      assert(t.state, "Tool must have state");
      assert(!t.state.toLowerCase().includes("nativ"), "State must NOT contain 'nativ'");
    });
  });

  // Verify specific states
  const lazyFn = results.cockpitFunctions.find(f => f.id === "lazyload");
  const lsLazy = lazyFn.tools.find(t => t.name === "LiteSpeed");
  const elemLazy = lazyFn.tools.find(t => t.name === "Elementor");
  assert.strictEqual(lsLazy.state, "PÅ", "LiteSpeed lazy must be PÅ");
  assert.strictEqual(elemLazy.state, "AV", "Elementor lazy must be AV");
  assert.strictEqual(lazyFn.status, "optimal", "Lazyload status should be optimal when only LS is ON");
});

// Test 2: Double activation detection
runTest("Double activation conflict detection in functions", () => {
  const mockSys = { server: { type: "LiteSpeed" } };
  const mockElem = { version: "3.28.3", e_lazy_load_images: "active" };
  const mockSettings = { media_lazy: "1" };

  const results = context.analyzeSystem(mockSys, null, null, mockElem, mockSettings, "", "", null, null);
  const lazyFn = results.cockpitFunctions.find(f => f.id === "lazyload");
  assert.strictEqual(lazyFn.status, "danger", "Status must be danger on double activation");
  assert.strictEqual(lazyFn.statusText, "Dubbel aktivering", "Status text must be 'Dubbel aktivering'");
});

// Test 3: HTML headers verification
runTest("index.html Section Headers (Verktyg, Funktioner, Identifierade risker)", () => {
  const indexHtml = fs.readFileSync(__dirname + '/../index.html', 'utf8');

  assert(indexHtml.includes("Verktyg"), "Must contain Verktyg header");
  assert(indexHtml.includes("Funktioner"), "Must contain Funktioner header");
  assert(indexHtml.includes("Identifierade risker"), "Must contain Identifierade risker header");
  assert(!indexHtml.includes("Analyserade Verktyg (Klicka för att filtrera)"), "Old icon header 1 removed");
  assert(!indexHtml.includes("Funktioner & Aktiv Källa (Renodlat utan dubbletter)"), "Old icon header 2 removed");
});

// Test 4: Version consistency across all files
runTest("Version consistency (v2.4.30)", () => {
  const indexHtml = fs.readFileSync(__dirname + '/../index.html', 'utf8');
  const appCode = fs.readFileSync(__dirname + '/../js/app.js', 'utf8');
  const readmeCode = fs.readFileSync(__dirname + '/../README.md', 'utf8');
  const geminiCode = fs.readFileSync(__dirname + '/../gemini.md', 'utf8');

  assert(indexHtml.includes("v2.4.30"), "index.html must contain v2.4.30");
  assert(appCode.includes("v2.4.30") || appCode.includes("2.4.30"), "app.js must contain 2.4.30");
  assert(rulesCode.includes("v2.4.30") || rulesCode.includes("2.4.30"), "rules.js must contain 2.4.30");
  assert(exporterCode.includes("v2.4.30") || exporterCode.includes("2.4.30"), "exporter.js must contain 2.4.30");
  assert(readmeCode.includes("v2.4.30"), "README.md must contain v2.4.30");
  assert(geminiCode.includes("v2.4.30"), "gemini.md must contain v2.4.30");
});

// Test 5: Exporter Second Opinion report
runTest("Exporter Second Opinion markdown report", () => {
  const mockState = {
    activeSite: "https://example.com",
    sysInfo: { "wp-core": { version: "6.8.0" } },
    wooInfo: { active_gateways: [{ id: "kco", title: "Klarna Checkout" }] },
    wfInfo: { ip_header: "REMOTE_ADDR" },
    elemInfo: { css_print_method: "external" },
    scmInfo: { snippets: [] },
    uploadedSettings: { "optm-js_defer": 2, "cache-exc": "checkout\nkassa\ncart\nvarukorg" },
    analysisResults: {
      healthScore: 95,
      scoreBreakdown: { stability: 30, performance: 35, security: 15, config: 15 },
      alerts: [],
      cockpitTools: [],
      cockpitFunctions: []
    },
    editedSettings: {}
  };

  const mdReport = context.generateSecondOpinionMarkdown(mockState);
  assert(mdReport.includes("v2.4.30"), "Must contain v2.4.30 in header");
});

// Test 6: app.js syntax validation
runTest("app.js syntax & compilation check", () => {
  const appCode = fs.readFileSync(__dirname + '/../js/app.js', 'utf8');
  assert.doesNotThrow(() => {
    new vm.Script(appCode);
  }, "app.js must compile without syntax errors");
});

console.log("\n=========================================");
console.log(` ALL ${passedTests} TEST SUITES PASSED (0 ERRORS)     `);
console.log("=========================================");
