/**
 * Automated test suite for AreWee-Optimizer v2.4.29
 * Tests:
 * 1. Cockpit tools (8 items) and functions (5 items) generated by analyzeSystem
 * 2. Strict drop_uri validation (requires both checkout and cart)
 * 3. optm_js_defer = 2 enum export preservation
 * 4. Sync plugin PHP header security (no $query_token, version 2.4.29)
 * 5. Version consistency across all modules (v2.4.29)
 * 6. app.js syntax validation
 * 7. Second Opinion Markdown generation
 * 8. Clean slot cards validation (no btn-slot-info, no slot-verified-summary)
 * 9. Riskdetektor badge zero/critical/warning states
 */

const fs = require('fs');
const vm = require('vm');
const assert = require('assert');

console.log("=========================================");
console.log(" Running AreWee-Optimizer v2.4.29 Tests  ");
console.log("=========================================");

// Setup mock browser environment
const context = {
  console: console,
  TextEncoder: TextEncoder,
  TextDecoder: TextDecoder,
  window: {},
  document: {
    getElementById: () => null,
    querySelectorAll: () => [],
    createElement: () => ({ appendChild: () => {}, setAttribute: () => {}, style: {}, classList: { add: () => {}, remove: () => {} } })
  },
  navigator: { clipboard: { writeText: async () => {} } },
  localStorage: { getItem: () => null, setItem: () => {}, removeItem: () => {} },
  state: {
    rawInputs: {},
    parsedData: {},
    activeSite: "default",
    uploadMetadata: {},
    analysisResults: null,
    activeTab: "overview",
    activeRiskFilter: "all"
  }
};
vm.createContext(context);

// Load rules.js and exporter.js into context
const rulesCode = fs.readFileSync(__dirname + '/../js/rules.js', 'utf8');
const exporterCode = fs.readFileSync(__dirname + '/../js/exporter.js', 'utf8');

vm.runInContext(rulesCode, context);
vm.runInContext(exporterCode, context);

let passedTests = 0;

function runTest(name, fn) {
  try {
    fn();
    console.log(`✅ PASS: ${name}`);
    passedTests++;
  } catch (err) {
    console.error(`❌ FAIL: ${name}`);
    console.error(err);
    process.exit(1);
  }
}

// Test 1: Cockpit generation
runTest("Cockpit generation (8 tools, 5 functions)", () => {
  const mockSys = {
    server: { type: "LiteSpeed", php_version: "8.2.1", memory_limit: "512M" },
    active_plugins: [
      { name: "LiteSpeed Cache", version: "6.5.4", slug: "litespeed-cache" },
      { name: "WooCommerce", version: "9.6.0", slug: "woocommerce" },
      { name: "Wordfence Security", version: "7.11.0", slug: "wordfence" },
      { name: "Elementor", version: "3.25.0", slug: "elementor" }
    ],
    theme: { name: "Astra", version: "4.8.0" }
  };
  const mockWoo = {
    cart_page_id: 10,
    checkout_page_id: 11,
    cart_page_url: "https://example.com/varukorg/",
    checkout_page_url: "https://example.com/kassa/",
    active_gateways: [{ id: "kco", title: "Klarna Checkout" }]
  };
  const mockSettings = {
    "optm-js_defer": 2,
    "cache-exc": "checkout\nkassa\nvarukorg\ncart"
  };

  const results = context.analyzeSystem(mockSys, mockWoo, {}, {}, mockSettings, "", "");
  assert(results, "Results must exist");
  assert(Array.isArray(results.cockpitTools), "cockpitTools must be an array");
  assert.strictEqual(results.cockpitTools.length, 8, "Must have exactly 8 cockpit tools");
  assert(Array.isArray(results.cockpitFunctions), "cockpitFunctions must be an array");
  assert.strictEqual(results.cockpitFunctions.length, 5, "Must have exactly 5 cockpit functions");

  // Verify WooCommerce tool has gateway protection subtext
  const wooTool = results.cockpitTools.find(t => t.id === "woocommerce");
  assert(wooTool, "WooCommerce tool must exist");
  assert(wooTool.subtext.includes("Klarna Checkout") || wooTool.subtext.includes("Gateway"), "WooCommerce must mention gateway");

  // Verify functions don't contain parentheses in source
  results.cockpitFunctions.forEach(fn => {
    assert(fn.source, "Function must have a source defined");
    assert(!fn.source.includes("("), `source should not contain parentheses: ${fn.source}`);
  });
});

// Test 2: Strict drop_uri validation
runTest("Strict drop_uri validation requires both checkout and cart", () => {
  const opt = { id: "drop_uri", type: "textarea", recommended: "^checkout\n^kassa\n^varukorg\n^cart" };
  const envWoo = { hasWooCommerce: true };

  // Case A: Missing cart
  const badSettingsA = { "cache-exc": "checkout\nkassa" };
  const compA = context.getOptionComparison(opt, badSettingsA, envWoo);
  assert.strictEqual(compA.isMatches, false, "Should fail when cart is missing");

  // Case B: Has both cart and checkout
  const goodSettings = { "cache-exc": "checkout\nkassa\nvarukorg\ncart" };
  const compB = context.getOptionComparison(opt, goodSettings, envWoo);
  assert.strictEqual(compB.isMatches, true, "Should pass when both checkout and cart are present");
});

// Test 3: optm_js_defer = 2 export serialization
runTest("optm_js_defer = 2 export serialization preserved as numeric 2", () => {
  const currentSettings = { "optm_js_defer": 2 };
  const lscwpObj = context.translateKeysToLscwp(currentSettings);
  assert.strictEqual(lscwpObj["optm_js_defer"] !== undefined ? lscwpObj["optm_js_defer"] : lscwpObj["optm-js_defer"], 2, "optm_js_defer must be preserved as 2");

  const serializedData = context.php_serialize(lscwpObj);
  assert(serializedData.includes('i:2;') || serializedData.includes('s:1:"2";'), "Serialized PHP data must preserve value 2");
  assert(!serializedData.includes('i:0;'), "Serialized PHP data must not coerce 2 to 0");
});

// Test 4: Sync plugin PHP header security
runTest("Sync plugin PHP has strict header authentication and no $query_token", () => {
  const syncPhp = context.generateSyncPluginPhp();
  assert(!syncPhp.includes("$query_token"), "Must not accept token via URL query parameter");
  assert(syncPhp.includes("X-Optimizer-Token"), "Must check X-Optimizer-Token header");
  assert(syncPhp.includes("Authorization"), "Must check Authorization Bearer header");
  assert(syncPhp.includes("Version: 2.4.29"), "Sync plugin version must be 2.4.29");
});

// Test 5: Version consistency across exporter.js, rules.js, index.html
runTest("Version consistency across exporter.js, rules.js, index.html", () => {
  const indexHtml = fs.readFileSync(__dirname + '/../index.html', 'utf8');
  assert(indexHtml.includes("v2.4.29"), "index.html must have v2.4.29");
  assert(!indexHtml.includes("v2.4.28"), "index.html must not have any v2.4.28");
  assert(!indexHtml.includes("v2.4.27"), "index.html must not have any v2.4.27");
  assert(exporterCode.includes("v2.4.29") || exporterCode.includes("2.4.29"), "exporter.js must reference 2.4.29");
  assert(!exporterCode.includes("2.4.28"), "exporter.js must not reference 2.4.28");
  assert(!rulesCode.includes("2.4.28"), "rules.js must not reference 2.4.28");
});

// Test 6: app.js syntax check
runTest("app.js syntax validation", () => {
  const appCode = fs.readFileSync(__dirname + '/../js/app.js', 'utf8');
  assert(!appCode.includes("2.4.28"), "app.js must not reference 2.4.28");
  assert(appCode.includes("2.4.29"), "app.js must reference 2.4.29");
  const script = new vm.Script(appCode, { filename: "app.js" });
  assert(script, "app.js must parse cleanly");
});

// Test 7: Second Opinion Markdown Generation
runTest("generateSecondOpinionMarkdown produces comprehensive report", () => {
  const mockState = {
    activeSite: "example.com",
    apiUrl: "https://example.com",
    sysInfo: {
      "wp-core": { version: "6.8.0", site_url: "https://example.com" },
      "wp-server": { httpd_software: "LiteSpeed", php_version: "8.2.1" },
      "wp-plugins-active": { "litespeed-cache": {}, "woocommerce": {} }
    },
    wooInfo: {
      cart_page_url: "https://example.com/cart/",
      checkout_page_url: "https://example.com/checkout/"
    },
    wfInfo: { ip_header: "REMOTE_ADDR" },
    elemInfo: { css_print_method: "external" },
    scmInfo: { snippets: [] },
    uploadedSettings: { "optm-js_defer": 2, "cache-exc": "checkout\nkassa\ncart\nvarukorg" },
    analysisResults: {
      healthScore: 95,
      scoreBreakdown: { stability: 30, performance: 35, security: 15, config: 15 },
      alerts: [],
      cockpitTools: [],
      cockpitFunctions: []
    },
    editedSettings: {}
  };

  const mdReport = context.generateSecondOpinionMarkdown(mockState);
  assert(mdReport.includes("AreWee-Optimizer: Fullständig Site-Report"), "Must contain report header");
  assert(mdReport.includes("v2.4.29"), "Must contain v2.4.29 header");
  assert(mdReport.includes("LiteSpeed"), "Must contain LiteSpeed details");
});

// Test 8: Clean slot cards verification
runTest("Clean slot cards verification in index.html", () => {
  const indexHtml = fs.readFileSync(__dirname + '/../index.html', 'utf8');
  assert(!indexHtml.includes("btn-slot-info"), "Must not contain btn-slot-info buttons");
  assert(!indexHtml.includes("slot-help-modal"), "Must not contain slot-help-modal");
  assert(!indexHtml.includes("slot-verified-summary"), "Must not contain slot-verified-summary elements");
});

console.log(`\n🎉 All ${passedTests} automated tests passed with 0 errors!`);
